Updated Profile Query variables section
MicrosoftDocs/OfficeDocs-MicrosoftSearch pull request #174
Opened 2021-06-16 06:53 UTC by Revathi-b

As Jeff suggested, I've added a Profile Query variables section below the Create the search vertical section.

2021-06-16 13:31 UTC, jeffkizn requested changes
Needs grammar edits too. Once this is published I suggest opening a review with pubops.

2021-06-16 13:31 UTC, jeffkizn commented on MicrosoftSearch/customize-search-page.md
> +    Profile {
This is not display like this unless you format it with tags like ```JSON

2021-06-16 13:31 UTC, jeffkizn commented on MicrosoftSearch/customize-search-page.md
> +Guidelines to be followed for invoking profile attributes. A typical structure of a profile resource is given below.
This is a fragment. Can you elaborate on the "Guidelines" sentence.

2021-06-16 13:31 UTC, jeffkizn commented on MicrosoftSearch/customize-search-page.md
> +## **Note**:
Please use !NOTE markdown syntax to format this as a note vs a new section

2021-06-16 18:05 UTC, AnjanaValsan commented on MicrosoftSearch/customize-search-page.md
> +Guidelines to be followed for invoking profile attributes. A typical structure of a profile resource is given below.
Guidelines are the syntax to be followed for invoking the Profile Query variables. The single and multi-string formats as mentioned in the emails example below this sentence.

2021-06-16 18:08 UTC, AnjanaValsan commented on MicrosoftSearch/customize-search-page.md
> +    Profile {
Shall we use this representation as reference to make edits to the sections where JSON snippets are used?
https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta#json-representation

2021-06-17 15:15 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +You can use a limited set of [Keyword Query Language (KQL)](/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference) to narrow the scope. This page lists the properties that a
"This page lists the properties that are available." I am not clear on what page is being referred to here. Is it the page linked earlier or the one being read currently. I think this sentence can be dropped.

2021-06-17 15:16 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +KQL also supports the use of Profile query variables to refine results under the vertical.
I would suggest refraining from using the word "refine". It could be confused with filters/refiners.

2021-06-17 15:18 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +Query variables are used in KQL query section of a vertical to provide dynamic data as an input to the query of a vertical. Profile query variables fetch values from the signed-in user’s [profile](ht
"Query variables are used in KQL query section of a vertical" - drop the KQL part. If the admin UI is being referred to then the section is called 'Query'.

2021-06-17 15:25 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +## Profile Query variables
@AnjanaValsan Looking at the overall structure of the page, I think this section can be added post Step 3. A search admin reading the page would be looking for instructions on creating a vertical and result type and adding profile query variable would be an additional setting that only some would look for. 

My suggestion is to retain this statement - "KQL also supports the use of Profile query variables to refine results under the vertical." and make the "profile query variables" part hyperlinked. For those who are interested in this, they can jump to the section easily. For others, they can understand how to create vertical by reading the rest of the article without first going through this big section.

2021-06-17 15:27 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +Query variables are used in KQL query section of a vertical to provide dynamic data as an input to the query of a vertical. Profile query variables fetch values from the signed-in user’s [profile](ht
Suggestion - Instead of saying "Profile query variables fetch values from the **signed-in user’s**" call them user performing search or search user. It makes it more relevant to the activity that the user is performing.

2021-06-17 15:35 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +Query variables are used in KQL query section of a vertical to provide dynamic data as an input to the query of a vertical. Profile query variables fetch values from the signed-in user’s [profile](ht
Suggestion for alternate framing of a sentence. 

Before - "For example, adding the following query template will narrow down the search results to show only those items where the author is the user performing the search. "

After - "For example, using the following query template in a vertical will show search results where the author of each result matches the user performing the search. "

2021-06-17 15:39 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +[Profile resource](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta) exposes properties as collections. For example, information related to email addresses is exposed
Does the following sentence seem more complete and is it correct?

[Profile resource](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta) API exposes user properties as collections.

2021-06-17 15:40 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +[Profile resource](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta) exposes properties as collections. For example, information related to email addresses is exposed
Typoe - All properties available in the user profile **as** exposed as Query variables. ... It should be "are"

2021-06-17 15:41 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +**Syntax**: Profile.<Relationship.Property.PropertyName>
Perhaps preface this with a line - Here is the syntax that should be used in ... Its not clear where this syntax should be used though, in the vertical page?

2021-06-17 15:42 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +Guidelines to be followed for invoking profile attributes. A typical structure of a profile resource is given below.
I think what is not clear to me is where are these guidelines being used. Since there is a back and forth between information about the graph API and the query variable applicable in vertical, it is getting confusing.

2021-06-17 15:45 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +Only single value variables will be expanded and not the entire collection object. For instance, _{Profile.Collection2.Property2}_ will not expand since it's an object. _{Profile.Collection2.Property
I dont fully understand how this API is used. What is meant by "expansion" of single value variables?

2021-06-17 15:49 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +Only single value variables will be expanded and not the entire collection object. For instance, _{Profile.Collection2.Property2}_ will not expand since it's an object. _{Profile.Collection2.Property
"Path" is a managed property in SharePoint schema as well. Also by "path" , are you referring to the sharepoint site path? 

The single value entity part is also not clear.

2021-06-17 15:55 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +The “&#124;” operator should be used for expanding multi-value variables. For more examples on Profile expansion, please refer to the table below.
The following line 

The “&#124;” operator should be used for expanding multi-value variables.

 can move up right after "I think this part can be moved up right after this line . "Multiple instances for a collection will be expanded depending on the syntax used.""

2021-06-30 06:44 UTC, Revathi-b commented
@AnjanaValsan @jypal6 I have updated the document with the latest string changes. Please review and let me know if you want me to make any changes.

2021-07-05 04:58 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +For example, under the “Tickets” vertical, if you wish to display only tickets that are assigned to the signed-in user, you can specify the following query under the query section of the respective v
In this sentence, you are talking about Search page and the admin UX. Can you please add context so that the user can differentiate between the tow. 
Something like this perhaps:
"For example, If you want to create a “Tickets” vertical where a signed-in user can search for tickets assigned to them, you can specify the following query under the "Query" section of the respective vertical during the vertical creation in the administration page. "

2021-07-05 04:59 UTC, jypal6 commented on MicrosoftSearch/customize-search-page.md
> +- If you wish to resolve all the values of the address attribute, you have to use the Multi-value expansion syntax as shown below. Here, the query
"Multi-value" shouldn't this be in small caps

2021-07-05 05:04 UTC, jypal6 approved these changes
Approving the document with some comments

2021-07-06 03:46 UTC, Revathi-b commented
Hi @jypal6 
Resolved all the comments, including grammar checks. Requesting you to merge and publish the document. Thanks

2021-07-06 15:33 UTC, jeffkizn approved these changes

2021-07-06 15:34 UTC, merged