Update graph-connector-agent.md
MicrosoftDocs/OfficeDocs-MicrosoftSearch pull request #252
Opened 2022-05-02 06:38 UTC by VivekKumarG

Updating permissions requirement for GCA

2022-05-02 21:23 UTC, jeffkizn requested changes

2022-05-02 21:23 UTC, jeffkizn commented on MicrosoftSearch/graph-connector-agent.md
> +   | [ExternalItem.ReadWrite.All](/graph/permissions-reference#application-permissions-52) | Optional |
@VivekKumarG THis permission is shown as optional but doesn't state why or when I should choose to add this. Can you clarify that point or delete this permission?

2022-05-02 21:23 UTC, jeffkizn commented on MicrosoftSearch/graph-connector-agent.md
> +  <!--- | [ExternalConnection.ReadWrite.OwnedBy](/graph/permissions-reference#application-permissions-52) | Required for Graph connector SDK | --->
Why is this line included but commented? Can you include it or delete it?

2022-05-03 16:23 UTC, VivekKumarG commented on MicrosoftSearch/graph-connector-agent.md
> +   | [ExternalItem.ReadWrite.All](/graph/permissions-reference#application-permissions-52) | Optional |
@jeffkizn Made the required change.

2022-05-03 16:23 UTC, VivekKumarG commented on MicrosoftSearch/graph-connector-agent.md
> +  <!--- | [ExternalConnection.ReadWrite.OwnedBy](/graph/permissions-reference#application-permissions-52) | Required for Graph connector SDK | --->
@jeffkizn Deleted the comment

2022-05-03 16:50 UTC, jeffkizn approved these changes

2022-05-03 16:50 UTC, merged