Modified strings for Querystring variables
MicrosoftDocs/OfficeDocs-MicrosoftSearch pull request #254
Opened 2022-05-05 04:28 UTC by Revathi-b

Modified strings for Querystring variables @AnjanaValsan

2022-05-05 15:46 UTC, jeffkizn requested changes

2022-05-05 15:46 UTC, jeffkizn commented on MicrosoftSearch/manage-verticals.md
> +You can use Query String variables to contextualize search results based on user interaction with SharePoint sites. Query string variables allows you to pass key-value pairs in the search URL to ensu
This is very abstract; the previous text was more human. Can you rephrase this to more common language?

2022-05-06 09:18 UTC, Revathi-b commented on MicrosoftSearch/manage-verticals.md
> +You can use Query String variables to contextualize search results based on user interaction with SharePoint sites. Query string variables allows you to pass key-value pairs in the search URL to ensu
@jeffkizn @AnjanaValsan 
Users were confused about this feature with the filters feature, and that’s the reason we thought of modifying the content.

Old content
You can use Query String variables to contextualize search results based on user interaction with SharePoint sites.

Below are the four proposed contents, and please feel free to share your thoughts on the content.

- You can modify search results based on user interaction with SharePoint sites using query string variables.
- Using query string variables, you can refine search results based on user interaction with SharePoint sites.
- Query String variables enable you to personalize search results based on how users interact with SharePoint sites.
- You can customize search results based on user interaction with SharePoint sites using query string variables.

2022-05-06 09:44 UTC, Revathi-b commented on MicrosoftSearch/manage-verticals.md
> +- Query string variables is not supported in Microsoft Search in Bing and Microsoft Search in Office.
@jeffkizn Query string variables are only supported on SharePoint sites.

2022-05-06 14:49 UTC, merged